### ISSUE TITLE
Please consider a new release and updating dependencies

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.emby#24]
Please consider creating (and releasing) a new release.

package.json states 1.0.5
io-package.json states 1.0.3
npm lists 1.02 
...

Thats confuding for users and listing at iobroker repositories is outdated because of this.

-------

In addtion please consider updateing dependencies, i.e. you are using adapter-core 1.x.x; current version 3.0.4. This might cause problems in future.

If you need any help or assitance please let uas (me) know.

Thanks
mcm2957

**Comment by thewhobox** [comment]
As i mentioned before i don't have a iobroker instance.
So i don't know the current versions.

If you now please make a pull-request and i will merge it.

Thanks

**Comment by thewhobox** [comment]
Also there seems to be a problem with the commands as button.
What is the current way to use this?

**Comment by mcm1957** [comment]
> Also there seems to be a problem with the commands as button.

What command as buttons you refer to?

**Comment by thewhobox** [comment]
Play, Pause, Mute, etc

**Comment by mcm1957** [comment]
> As i mentioned before i don't have a iobroker instance. So i don't know the current versions.
> 
> If you now please make a pull-request and i will merge it.
> 
> Thanks

OK, I can create a PR
- adding current standard tests
- adding @alcazones release script

But if you do not have a working development environment you will not be able to create a clean release. Creating a Release is not possible by PR, this must be done at the repository.

If you do not have and do not plan to set up a development environment we should eventually discusse the future. I can offer to migrate the adapter to iobroker community organisation. There multiple developers would have access to code and could create releaeses. Of course you will have normale read/write access to your code too if you want to have.

If you want to setup a dev environemnt at your site I (and others) will try to guide an halp you too. This is NO try to get your code in any way. Especially I cannot really maintain the code itself as I do not have any matching environment. I can only assist in releasemenagement etc.

Please let me / us know what direction you prefer. Its solely your decision.

AND THANKS VERY MUCH for the work you did until now. THANK YOU

**Comment by mcm1957** [comment]
> Play, Pause, Mute, etc

Ok, thats  a issue different from environment. Must be checked by any dev who has a matching device.
I could ask at developer telegram channel if someone has time to take a look.

**Comment by thewhobox** [comment]
Sure we can Transfer it to the community.
It would be great of I had permissions on the repo so I can help you if there are other Bugs in the future.

Where do i need to Transfer it to?

**Comment by apachelance** [comment]
Great idea.

**Comment by mcm1957** [comment]
Well
I ll answer from mobile for now. I m on holiday next week thuesday to friday. I can try to perform the transfer until monday but i cannot promise.

YOU must do the following to initialize the transfer

Log in to npm and go to  the adapter package pafe. Open setup and send an INVITE to mcm1957

Log in to github and go to adapter repository.
Open setzp and scroll down to DANGER ZONE
Initialize a transfer of the repository to mcm1957.

I will transfer the repo to iobroker community adapters immidiatly afterwards and add you as maintainer. The transfer using me as intermediate is required as only administrative members of github orga can import a repository.

Plese ask if any more questions.
My direct mail is mcm57@gmx.at.

**Comment by thewhobox** [comment]
You will have to delete your repo first.
Otherwise I cant Transfer it to your Account on Github.

**Comment by mcm1957** [comment]
Sorry, I've forgotten my fork.
Have it deleted now.

npm invite was successfull

THANKS A LOT

**Comment by mcm1957** [comment]
Thanks for transferring.

I already moved it to iobroker-community-adapters. You should have access there. If anything does not work as expected, please let me know.

I will have to do several adaptions (i.e. adapting repo urls). I will do this during the next days.

**Comment by thewhobox** [comment]
Transfer was successful.
Issue will be handled in #25
