### ISSUE TITLE
Adapter geht nicht mehr? 

### ISSUE THREAD

**Issue by tommyMX** [iobroker-community-adapters/ioBroker.emby#26]
Hi, 

hab grad den Adapter installiert und werde mit Errors erschlagen :-(

`Error: undefined is not a valid state value at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17) at AdapterClass._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5439:49) at AdapterClass.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5400:21) at W3CWebSocket.webMessage [as onmessage] (/opt/iobroker/node_modules/iobroker.emby/main.js:356:21) at W3CWebSocket._dispatchEvent [as dispatchEvent] (/opt/iobroker/node_modules/yaeti/lib/EventTarget.js:107:17) at W3CWebSocket.onMessage (/opt/iobroker/node_modules/websocket/lib/W3CWebSocket.js:234:14) at WebSocketConnection.<anonymous> (/opt/iobroker/node_modules/websocket/lib/W3CWebSocket.js:205:19) at WebSocketConnection.emit (node:events:517:28) at WebSocketConnection.processFrame (/opt/iobroker/node_modules/websocket/lib/WebSocketConnection.js:554:26) at /opt/iobroker/node_modules/websocket/lib/WebSocketConnection.js:323:40`

```
unhandled promise rejection: undefined is not a valid state value
Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

```

**Comment by mcm1957** [comment]
Wie /von wo hast du installiert?

**Comment by mcm1957** [comment]
Dürfte dup zu #23 sein. Der Fehler sollte mit Github Version behoben sein

**Comment by tommyMX** [comment]
Über die Iobroker Adapter Oberfläche

**Comment by tommyMX** [comment]
Also über GitHub installieren ? Ok versuche ich mal

**Comment by mcm1957** [comment]
Die versionen im repo sind veraltet. Korrektur gibts auf hithub. Veröffentlichung istv in Arbeit.

**Comment by thewhobox** [comment]
Auch vielen Dank an @mcm1957, dass er sich der Sache annimmt und sich um ein neues release kümmert.

**Comment by tommyMX** [comment]
@mcm1957 danke dir :-) sieht schon gut aus :-)

**Comment by mcm1957** [comment]
should be fixed with 1.1.1 (available at latest at 21.11.2023)

If problem still occures, please resond or open a new oissue.
